### PR TITLE
[DO NOT SUBMIT] Enable all breakpoints to be shown, not just breakpoints set by the proxy

### PR DESCRIPTION
**Pull request by iantalarico**
This is just a partial implementation for #19 as I wanted to see your opinions before I clean it up and write tests.

When I was looking through the implantation of the of DebugProxy I found it a little hard to work with as it was very focused on specific use cases and made assumptions about what consumers would want.  IMO I think it would be a little easier to start off with a more open model and as more users adopt it find common pain points that can we removed.

My general proposal is:
- rely on the breakpoint list from the Stackdriver Debugger API as the source of truth for breakpoints
- allow toggling of local vs non local breakpoints
- notify users of all changes to breakpoints (not just hits) as the Stackdriver Debugger API can return other useful information. 

Let me know what you think!

### CODE REVIEW

**Comment by iantalarico** [comment]
@ofrobots Ping

**Comment by eyqs** [comment]
Thanks for doing this! The code looks much cleaner now. Some notes:

1) Why were the remove all breakpoints functions removed?
2) Would it be better to add `localOnly` as an optional parameter in all the functions, rather than keep it as a global property?
3) Since `getBreakpointList` does not rely on `breakpointInfoMap` anymore, should you call `this.wrappers.debuggeesBreakpointsList` first? It's possible that users are not polling `updateBreakpointList`.
4) Feel free to address the TODO later. If no users care about the local breakpoint functionality, then it takes a bit of effort to check for changes.

**Comment by iantalarico** [comment]
1.  I don't think it adds too much from the user just manually calling delete on each breakpoint and enables users to remove a lot of data accidentally by calling delete when all breakpoints are shown.  

2. I need to think on this more.  But maybe?  Regardless of this specific case I think this the issue I'm having with this all is this is about ~300-400 lines of substantial code and with this change we lose another 100 lines.  Is the overhead of maintaining this in a useful generic way easier than the overhead of maintaining it separately in a few different places?  I don't expect creating Stackdriver Debugger UIs to be a common task.  Thoughts?

3. Yea that's probably a good call.

**Comment by eyqs** [comment]
How about exposing a `setLocalOnly` function instead of passing any `localOnly` parameters? This would correspond to users toggling a "only use local breakpoints" checkbox.

Please assign a TODO for me to implement checking for local breakpoint updates. I've thought about the situation a lot and can easily reuse some of the older code, and it's not worth it for you to worry about it.

**Comment by eyqs** [comment]
@iantalarico Do you still need this to be merged? I can make sure the tests pass and add new tests.

**Comment by iantalarico** [comment]
No, I lost track of this a bit, I made a work around of for this in my code.

**Pull request closed without merging**
